version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
    rust: "1.70"
  commands:
    - pip install maturin[patchelf]
    - cd sdk && maturin build
    - pip install sdk/target/wheels/*.whl
    - pip install -r sdk/docs/requirements.txt
    - sphinx-build -M html sdk/docs/source/ _readthedocs/
